[package]
name = "sd_importer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2.3.2"
chrono = "0.4"
rayon = "1.5.1"
indicatif = "0.15.0"
kamadak-exif = "0.5.5"

